This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./example.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file example.acn....done (202 entries accepted, 0 rejected).
Sorting entries.....done (1837 comparisons).
Generating output file example.acr....done (124 lines written, 0 warnings).
Output written in example.acr.
Transcript written in example.alg.
